### PR TITLE
fix: regression in zoom camera

### PR DESCRIPTION
**Pull request by NeatUnsou**
partially revert the changes that were causing the issue with #1334 in #1323
the problem in #1319 is still fixed

### CODE REVIEW

**Comment by Lazin3ss** [comment]
CameraZoomYBound reversion seems reasonable (I can't remember why I made that change, probably to fix a discrepancy with MUGEN 1.1 I can't remember right now), but I don't think ExtraBoundH change should be reverted. That change was done to emulate a MUGEN 1.1 behavior regarding boundhigh fluctuation based on zoom scaling. In MUGEN 1.1, boundhigh gets wider based on how much the stage was zoomed out.

MUGEN 1.1:
https://github.com/ikemen-engine/Ikemen-GO/assets/23774987/116836e7-3bfc-4984-90d5-8b3d7f8915be

Ikemen GO without zoom-based ExtraBoundH fluctuation:
https://github.com/ikemen-engine/Ikemen-GO/assets/23774987/66973266-5408-4e9a-8aa1-7a502bab0837

Ikemen GO with zoom-based ExtraBoundH fluctuation:
https://github.com/ikemen-engine/Ikemen-GO/assets/23774987/8122804f-48bf-4720-bce5-b79f1a7a64ec

**Comment by NeatUnsou** [comment]
I understand that the changes made to ExtraBoundH are intended to emulate the behavior of MUGEN 1.1
However, this behavior has a limitation that boundhigh is not reached unless the screen is zoomed out sufficiently.

As a consequence of this limitation, there is an issue when performing aerial combos with MVC chars.
Both chars stay close to each other while being airborne, and since the zoomout doesn't occur, the Y-scroll stops midway, preventing it from reaching the intended boundhigh limit.

In my view, this as one of the major flaws in MUGEN 1.1, and I am opposed to replicating it in ikemengo. 
I feel the existing ikemengo behavior where boundhigh remains constant regardless of zoom scaling state makes more sense.

**Comment by Lazin3ss** [comment]
Indeed it does, that being said, there might be MUGEN stages that are built with this limitation in mind, and not replicating it could potentially break them.

I think this might be enough of reason for us to start implementing `ikemenversion` flag on stages. That way, we can start pushing forward stagemaking towards what we think it makes sense (as opposed to complying to elecbyte rules), while, at the same time, mantaining full backwards compatibility with MUGEN 1.1.

**Comment by NeatUnsou** [comment]
reverted the zoom scaling behavior that adjusts ExtraBoundH like MUGEN 1.1, making it work only for stages with low zoomdelta values to avoid breaking the existing behavior. This ensures that stages designed with the assumption of MUGEN 1.1 behavior won't be affected while maintaining the functionality of the current ikemen go.

I believe this change maintains compatibility, but I agree with the suggestion that a new parameter might be necessary in the future, as the camera behavior being altered by zoomdelta seems strange way.

**Comment by Lazin3ss** [comment]
We can leave it like this until the next version, where we can add the ikemenversion flag.

**Pull request merged**
