### PR TITLE
Character select Skip Slot added

### PR DESCRIPTION
**Pull request by GaryCXJk**
As outlined by #538 .

### CODE REVIEW

**Comment by K4thos** [comment]
to be honest I don't like this idea at all, I don't think it should be merged. You can already title your cell exactly the same as in your change (cell.colNumber.rowNumber.skip) and it will skip just fine (ikemen, just like mugen, skips over non existing char references).

Lua scripts are often spaghetti coded and extremely bloated (desperately need refactoring down the road). Stuff like this is better suited for external modules, imo: https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-info#external-modules

I suggest joining discord to gather feedback about features ideas: https://discord.gg/tyASDfmn

**Comment by Rurouni-X** [comment]
> to be honest, I don't think this PR should be merged. You can already title your cell exactly the same as in your change (cell.colNumber.rowNumber.skip) and it will skip just fine (ikemen, just like mugen, skips over non existing char references).

Currently, cells have extra functions like offset, facing and their own cursors.
Considering all this, a method for skipping them doesn't seem like something out of line with the new features.
It's true that we can use "do not modify" lines for this, but with all the improvements wouldn't it be better for the screenpack to handle the select screen design instead of continuing to use MUGEN's hacky method?
Also, with this new feature it would not be mandatory to use a unique/custom select.def like this:
[select.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8885867/select.zip)
shot

This would benefit the end user as they wouldn't have to worry about messing up the roster organization or keeping a backup of select.def.

**Comment by K4thos** [comment]
> Considering all this, a method for skipping them doesn't seem like something out of line with the new features.

a method for skipping them already exists

**Comment by GaryCXJk** [comment]
I do have to respectfully disagree with that assessment, as I did think about the implications of changing it on a script level.

By using the current MUGEN method of skipping cells, you'll run into two issues. The first issue is that, because of the `moveoveremptyboxes` setting being set to 0, you have to set all the remaining boxes to something like randomselect in order for them to be visibly present. Sure, it isn't that big of a deal, but it does bring up a second issue.

Your select.def is bound by the layout.

This is an issue with MUGEN at the moment, where you can't just change a screenpack without having to make sure the select.def fits the current screenpack's character select screen. If a screenpack relies on cells being skipped, and you have already have a full select.def, you'll have to manually copy over each entry, making sure you copy the right amount of lines. With the `slot` feature, you'll run into an even bigger problem, as now, the lines copied over don't have to match the amount of lines that need to be replaced.

Now, while it is true that screenpacks can still require you to overwrite the Lua files, it'd more than likely be a lesser issue, as changing screenpacks again with a different set of Lua files won't likely cause problems with the select.def.

A final point that can be made here is, in theory, this change won't affect existing screenpacks. It'd be a whole different thing if it did. Could this be coded better? Most likely, for example, I really don't like how I added skips by just adding dummy characters, as it really is no different than how it has been done right now, and more ideally, you'd probably want a separate def file to define layouts. But using this feature or not won't matter. In the end, this is mostly a convenience change rather than an absolute requirement.

**Comment by Windblade-GR01** [comment]
On this case I agree with Gary.
Having to copy-paste over 1000 times on a file can not be called "not really a workaround".

It's a incredibly tedious process and it creates problems.

**Comment by K4thos** [comment]
The feature of having the same select.def functional with different screenpacks indeed sounds nice, I have not thought about it from this perspective.

Will merge with little changes (no point in searching for file existence when it's known that slot is dummy from the get go, should save some loading time in larger screenpacks).

Thanks for contribution.

**Pull request merged**
