### PR TITLE
Added prandom trigger

### PR DESCRIPTION
**Pull request by Alceris**
Can't build to test if this works, but I see no reason why it shouldn't.

### CODE REVIEW

**Comment by Lazin3ss** [comment]
Did a quick test, can't build from it because of an overflow in constant declaration

From the compiler:
`src\bytecode.go:220:2: cannot use iota + 110 (untyped int constant 256) as OpCode value in constant declaration (overflows)`

**Comment by Alceris** [comment]
Yeah, fuck this language.

**Comment by Lazin3ss** [comment]
The implementation is fine in itself, the only thing is, you have to do it via `OC_ex`. Example:
https://github.com/ikemen-engine/Ikemen-GO/commit/52f768a506e26488ae74a76e172b67831abe7bb0

I'd recommend you force-pushing the same commit in your branch, but oriented towards `OC_ex` instead.

**Comment by Alceris** [comment]
I do not understand, but have done.

**Comment by Lazin3ss** [comment]
Engine builds and trigger works as expected, this can be merged.

**Comment by K4thos** [comment]
I don't see a purpose of this. What is this trigger for?

**Comment by Alceris** [comment]
It returns the same value as the previous random trigger without changing it, so you don't need to store the value in order to check the same random number multiple times in one frame.

**Comment by K4thos** [comment]
as discussed on discord this feature is not that useful from zss perspective, so I'm closing it. But thanks for PR.

**Pull request closed without merging**
