### PR TITLE
fix: Target camera height/Y when using verticalfollow and zoom

### PR DESCRIPTION
**Pull request by Kasasagi77**
This is the biggest change/fix for #1652, however please do not close the issue yet - the scrolling still seems to be choppy to me and I am still testing it.

@Eiton - you may want to review as this changes the camera code again.

### CODE REVIEW

**Comment by potsmugen** [comment]
So far so good. This fixes an issue I'd posted on Discord but not here yet.

**Comment by Kasasagi77** [comment]
OK.

To clarify - I want to continue testing the #1652 issue, but I do think that this PR is an unambigous fix and can be merged even before fully closing #1652.

**Comment by Eiton** [comment]
Looks good. Have you tried using targetScale instead of scale? I think it should be better.

**Comment by Eiton** [comment]
This is not need when #1760 is merged

**Comment by Kasasagi77** [comment]
OK then, I will continue testing when #1760 is merged.

Closing this then.

**Pull request closed without merging**
